/**
 * HEAT Embeddable Widget — ZIP-level attention summary.
 * Usage: <div id="heat-widget" data-zip="07060"></div>
 *        <script src="https://heat-map.org/exports/embed.js"></script>
 *
 * Generated by HEAT Publisher (Shift 20).
 */
(function() {
  'use strict';

  // Auto-detect base URL from the embed script's own src attribute,
  // so the widget works from any host (GitHub Pages, custom domain, etc.)
  var SCRIPT_SRC = (function() {
    var scripts = document.getElementsByTagName('script');
    for (var i = 0; i < scripts.length; i++) {
      if (scripts[i].src && scripts[i].src.indexOf('embed.js') !== -1) {
        return scripts[i].src.replace(/exports\/embed\.js.*$/, '');
      }
    }
    return './';
  })();
  var DATA_URL = SCRIPT_SRC + 'data/attention_results.json';
  var SCHEMA_VERSION = '1.0.0';

  var STATE_COLORS = {
    QUIET:              '#E8F5E9',
    MODERATE:           '#FFF9C4',
    ELEVATED_ATTENTION: '#FFE0B2',
    HIGH_ATTENTION:     '#FFCDD2'
  };

  var STATE_LABELS = {
    QUIET:              'Baseline',
    MODERATE:           'Moderate',
    ELEVATED_ATTENTION: 'Elevated',
    HIGH_ATTENTION:     'High Attention'
  };

  function init() {
    var containers = document.querySelectorAll('[id="heat-widget"]');
    if (!containers.length) return;

    fetch(DATA_URL)
      .then(function(r) { return r.json(); })
      .then(function(data) {
        var results = data.results || data.attention_results || [];
        containers.forEach(function(el) {
          var zip = el.getAttribute('data-zip') || '07060';
          var match = results.find(function(r) { return r.zip === zip; });
          render(el, zip, match);
        });
      })
      .catch(function(err) {
        containers.forEach(function(el) {
          el.innerHTML = '<p style="color:#999;font-size:12px;">HEAT data unavailable.</p>';
        });
      });
  }

  function render(el, zip, data) {
    var state = data ? data.state : 'QUIET';
    var score = data ? data.score : 0;
    var color = STATE_COLORS[state] || STATE_COLORS.QUIET;
    var label = STATE_LABELS[state] || 'Unknown';

    el.style.cssText = 'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;'
      + 'border:1px solid #ddd;border-radius:8px;padding:12px 16px;max-width:280px;'
      + 'background:' + color + ';';

    el.innerHTML = ''
      + '<div style="font-size:11px;color:#666;margin-bottom:4px;">HEAT Civic Attention</div>'
      + '<div style="font-size:18px;font-weight:600;">ZIP ' + zip + '</div>'
      + '<div style="font-size:14px;margin-top:4px;">' + label + '</div>'
      + '<div style="font-size:12px;color:#888;margin-top:6px;">Score: ' + score.toFixed(2)
      + ' &middot; Schema v' + SCHEMA_VERSION + '</div>'
      + '<div style="font-size:10px;color:#aaa;margin-top:4px;">'
      + 'Delayed aggregate &mdash; not real-time. <a href="' + SCRIPT_SRC + '" target="_blank" style="color:#1a73e8;">Learn more</a></div>';
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
